#!/bin/bash

# CLI-Frontend Alignment Test Script
# This script helps verify that CLI commands generated by the UI produce identical results
# to running backtests via the UI.

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default test parameters (matching UI example)
MODE="${1:-report}"  # 'fast' or 'report'
INSTRUMENT="${2:-BTCUSDT}"
DATASET="${3:-day-2023-05-23}"
CONFIG="${4:-binance_futures_btcusdt_l2_trades_config.json}"
START_TIME="${5:-2023-05-23T02:00:00Z}"
END_TIME="${6:-2023-05-23T02:05:00Z}"
SNAPSHOT_MODE="${7:-both}"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}CLI-Frontend Alignment Test${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "Mode: ${YELLOW}${MODE}${NC}"
echo -e "Instrument: ${YELLOW}${INSTRUMENT}${NC}"
echo -e "Dataset: ${YELLOW}${DATASET}${NC}"
echo -e "Config: ${YELLOW}${CONFIG}${NC}"
echo -e "Start Time: ${YELLOW}${START_TIME}${NC}"
echo -e "End Time: ${YELLOW}${END_TIME}${NC}"
echo -e "Snapshot Mode: ${YELLOW}${SNAPSHOT_MODE}${NC}"
echo ""

# Build CLI command
CONFIG_PATH="external/data_downloads/configs/${CONFIG}"

FLAGS=(
  "--instrument ${INSTRUMENT}"
  "--dataset ${DATASET}"
  "--config ${CONFIG_PATH}"
  "--start ${START_TIME}"
  "--end ${END_TIME}"
  "--snapshot_mode ${SNAPSHOT_MODE}"
)

if [ "$MODE" = "fast" ]; then
  FLAGS+=("--fast")
elif [ "$MODE" = "report" ]; then
  FLAGS+=("--report")
  # Optionally add export_ticks for report mode
  # FLAGS+=("--export_ticks")
fi

CLI_CMD="python backend/run_backtest.py ${FLAGS[*]}"

echo -e "${BLUE}Generated CLI Command:${NC}"
echo -e "${GREEN}${CLI_CMD}${NC}"
echo ""

# Check if Docker Compose is available
if ! command -v docker-compose &> /dev/null; then
  echo -e "${RED}Error: docker-compose not found${NC}"
  echo "Please install docker-compose or use Docker Desktop"
  exit 1
fi

# Check if backend container is running
if ! docker-compose ps backend | grep -q "Up"; then
  echo -e "${YELLOW}Warning: Backend container may not be running${NC}"
  echo "Attempting to start services..."
  docker-compose up -d backend
  sleep 5
fi

echo -e "${BLUE}Executing CLI command in Docker container...${NC}"
echo ""

# Execute command in Docker container
OUTPUT=$(docker-compose exec -T backend bash -c "cd /app && ${CLI_CMD}" 2>&1)
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo -e "${RED}CLI command failed with exit code ${EXIT_CODE}${NC}"
  echo -e "${RED}Output:${NC}"
  echo "$OUTPUT"
  exit 1
fi

echo "$OUTPUT"
echo ""

# Extract run_id from output
RUN_ID=$(echo "$OUTPUT" | grep -oP "Run ID: \K[^\s]+" | head -1)

if [ -z "$RUN_ID" ]; then
  echo -e "${YELLOW}Warning: Could not extract run_id from output${NC}"
  echo "Please check the output above for the run_id"
else
  echo -e "${GREEN}✓ CLI execution successful${NC}"
  echo -e "${GREEN}Run ID: ${RUN_ID}${NC}"
  echo ""
  
  # Determine result file path
  if [ "$MODE" = "fast" ]; then
    RESULT_FILE="backend/backtest_results/fast/${RUN_ID}/summary.json"
  else
    RESULT_FILE="backend/backtest_results/report/${RUN_ID}/summary.json"
  fi
  
  echo -e "${BLUE}Result file location:${NC}"
  echo -e "${GREEN}${RESULT_FILE}${NC}"
  echo ""
  
  # Check if result file exists
  if docker-compose exec -T backend test -f "/app/${RESULT_FILE}"; then
    echo -e "${GREEN}✓ Result file exists${NC}"
  else
    echo -e "${YELLOW}Warning: Result file not found at expected location${NC}"
  fi
fi

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Next Steps for Manual Comparison:${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "1. Run the same backtest via UI:"
echo "   - Navigate to http://localhost:5173/run"
echo "   - Fill form with the same parameters:"
echo "     • Instrument: ${INSTRUMENT}"
echo "     • Dataset: ${DATASET}"
echo "     • Config: ${CONFIG}"
echo "     • Start Time: ${START_TIME}"
echo "     • End Time: ${END_TIME}"
echo "     • Snapshot Mode: ${SNAPSHOT_MODE}"
if [ "$MODE" = "fast" ]; then
  echo "     • Enable Fast Mode"
else
  echo "     • Enable Report Mode"
fi
echo "   - Click 'Run Backtest'"
echo "   - Note the run_id from results panel"
echo ""
echo "2. Compare results:"
echo "   - CLI result: ${RESULT_FILE}"
echo "   - UI result: backend/backtest_results/${MODE}/<ui_run_id>/summary.json"
echo ""
echo "3. Compare JSON files (excluding run_id and timestamps):"
echo "   docker-compose exec backend bash -c 'cd /app && \\"
echo "     jq -S \"del(.run_id, .metadata.timestamp)\" ${RESULT_FILE} > /tmp/cli_result.json && \\"
echo "     jq -S \"del(.run_id, .metadata.timestamp)\" backend/backtest_results/${MODE}/<ui_run_id>/summary.json > /tmp/ui_result.json && \\"
echo "     diff /tmp/cli_result.json /tmp/ui_result.json'"
echo ""
echo "4. Verify both results appear in comparison page:"
echo "   - Navigate to http://localhost:5173/"
echo "   - Both run_ids should appear in the table"
echo "   - Summary metrics should match"
echo ""
echo -e "${GREEN}Expected: Results should match exactly except for run_id and metadata timestamps${NC}"

